import { makeStyles } from '@alveole/theme';

export const useStyles = makeStyles(({ spacing, color, text }) => ({
  accordion: {
    width: '100%',
    borderBottomWidth: 1,
  },
  accordionLight: {
    borderColor: 'white',
  },
  accordionDefault: {
    borderColor: color.border['default-grey'],
  },
  accordionRounded: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.border['default-grey'],
    overflow: 'hidden',
  },
  accordionItemTrigger: {
    borderWidth: 0,
    padding: 0,
  },
  accordionItemHeader: {
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: spacing('075'),
    paddingBottom: spacing('075'),
    paddingLeft: spacing('100'),
    paddingRight: spacing('100'),
    alignItems: 'flex-start',
    gap: spacing('075'),
    alignSelf: 'stretch',
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
  },
  accordionItemHeaderAlt: {
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: spacing('075'),
    paddingBottom: spacing('075'),
    paddingLeft: spacing('100'),
    paddingRight: spacing('100'),
    alignItems: 'flex-start',
    gap: spacing('075'),
    alignSelf: 'stretch',
    backgroundColor: color.background['alt-grey'],
    borderWidth: 0,
  },
  accordionItemHeaderOutline: {
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: spacing('075'),
    paddingBottom: spacing('075'),
    paddingLeft: spacing('100'),
    paddingRight: spacing('100'),
    alignItems: 'flex-start',
    gap: spacing('075'),
    alignSelf: 'stretch',
    borderWidth: 0,
    backgroundColor: '#FFFFFF',
    outlineWidth: 1,
    outlineColor: color.border['default-grey'],
    outlineStyle: 'solid',
  },
  accordionItemHeaderOpen: {
    backgroundColor: color.background['default-active'],
  },
  accordionItemLabel: {
    ...text['Corps de texte'].SM.Medium,
  },
  accordionItemContent: {
    padding: spacing('100'),
    paddingBottom: spacing('150'),
  },
  accordionAfterLabel: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: color.border['default-grey'],
  },
}));
