// This file is generated. Do not edit manually.
// Source: src/ui/Toast/Toast.stories.tsx

export const All = () => "export const All = () => {\n  const toast = useToast();\n\n  const defaultToast = () => toast.present('Default', 'Message');\n  const successToast = () => toast.present('Success', 'Message', { variant: 'success' });\n  const errorToast = () => toast.present('Error', 'Message beaucoup plus long', { variant: 'error' });\n  const infoToast = () => toast.present('Information', 'Message', { variant: 'info' });\n  const infoToastMultiLine = () =>\n    toast.present('Information', 'Message beaucoup plus long avec retour à la ligne.\\nDeuxième ligne', {\n      variant: 'info',\n    });\n  const withoutMessageToast = () => toast.present('Sans message');\n  const withoutMessageToastError = () => toast.present('Sans message', undefined, { variant: 'error' });\n  const withCustomIcon = () => toast.present('Avec icon custom', undefined, { icon: 'Worm' });\n\n  return (\n    <Box display=\"flex\" flexDirection=\"column\" gap={16}>\n      <Box display=\"flex\" flexDirection=\"column\" gap={'050'}>\n        <Button title=\"Default toast\" variant=\"primary\" onPress={defaultToast} />\n        <Button title=\"Success toast\" variant=\"primary\" onPress={successToast} />\n        <Button title=\"Error toast\" variant=\"primary\" onPress={errorToast} />\n        <Button title=\"Info toast\" variant=\"primary\" onPress={infoToast} />\n        <Button title=\"Message long\" variant=\"primary\" onPress={infoToastMultiLine} />\n        <Button title=\"Without message toast\" variant=\"primary\" onPress={withoutMessageToast} />\n        <Button title=\"Without message toast error\" variant=\"primary\" onPress={withoutMessageToastError} />\n        <Button title=\"WithCustomIcon\" variant=\"primary\" onPress={withCustomIcon} />\n      </Box>\n      <Box display=\"flex\" flexDirection=\"column\" gap={4}>\n        <Typography>{`Le fichier _layout.tsx doit inclure la balise <Toasts> pour fonctionner`}</Typography>\n        <Highlight language=\"tsx\">\n          {`\n            <Toasts>\n              <Stack screenOptions={{ headerShown: false }} />\n            </Toasts>\n          `}\n        </Highlight>\n      </Box>\n    </Box>\n  );\n};";

export const storySources = {
  All,
} as const;

export type StorySourceName = keyof typeof storySources;
