// This file is generated. Do not edit manually.
// Source: src/ui/ActionMenu/ActionMenu.stories.tsx

export const Default = () => "export const Default = () => {\n  const alignments = [\n    'top',\n    'right',\n    'bottom',\n    'left',\n    'top-start',\n    'top-end',\n    'right-start',\n    'right-end',\n    'bottom-start',\n    'bottom-end',\n    'left-start',\n    'left-end',\n  ] as const;\n\n  return (\n    <Box\n      display=\"flex\"\n      flexWrap=\"wrap\"\n      gap=\"1W\"\n      flexDirection=\"row\"\n      justify-content=\"center\"\n      align-items=\"center\"\n      width=\"100%\"\n    >\n      {alignments.map(alignment => (\n        <ActionMenu\n          key={alignment}\n          placement={alignment}\n          renderTrigger={() => <Button variant=\"secondary\" title={alignment} />}\n        >\n          <ActionMenu.Item title=\"Contenu de l'action menu\" icon=\"Settings\" selected />\n          <ActionMenu.Item title=\"Contenu de l'action menu\" icon=\"Copy\" />\n          <ActionMenu.Item title=\"Contenu de l'action menu\" icon=\"Trash\" />\n        </ActionMenu>\n      ))}\n    </Box>\n  );\n};";

export const Filters = () => "export const Filters = () => {\n  const epics = ['Refonte design', 'Onboarding', 'Facturation'];\n  const types = ['Bug', 'Story', 'Tâche'];\n  const filtresRapides = ['Assigné à moi', 'En cours', 'En retard'];\n\n  const [epicFilter, setEpicFilter] = React.useState<string | null>(null);\n  const [typeFilter, setTypeFilter] = React.useState<string | null>(null);\n  const [filtresRapidesFilter, setFiltresRapidesFilter] = React.useState<string[]>([]);\n\n  return (\n    <Box display=\"flex\" flexDirection=\"row\" gap=\"2\" align-items=\"center\">\n      <ActionMenu\n        placement=\"bottom-start\"\n        scrollable={false}\n        renderTrigger={() => (\n          <Button\n            variant=\"secondary\"\n            title=\"Epic\"\n            endIcon=\"ChevronDown\"\n            selected={epicFilter !== null}\n          />\n        )}\n      >\n        <ActionMenu.Item\n          title=\"Toutes les épics\"\n          selected={epicFilter === null}\n          onPress={() => setEpicFilter(null)}\n        />\n        {epics.map(epic => (\n          <ActionMenu.Item\n            key={epic}\n            title={epic}\n            selected={epicFilter === epic}\n            onPress={() => setEpicFilter(epicFilter === epic ? null : epic)}\n          />\n        ))}\n      </ActionMenu>\n\n      <ActionMenu\n        placement=\"bottom-start\"\n        scrollable={false}\n        renderTrigger={() => (\n          <Button\n            variant=\"secondary\"\n            title=\"Type\"\n            endIcon=\"ChevronDown\"\n            selected={typeFilter !== null}\n          />\n        )}\n      >\n        <ActionMenu.Item\n          title=\"Tous les types\"\n          selected={typeFilter === null}\n          onPress={() => setTypeFilter(null)}\n        />\n        {types.map(type => (\n          <ActionMenu.Item\n            key={type}\n            title={type}\n            selected={typeFilter === type}\n            onPress={() => setTypeFilter(typeFilter === type ? null : type)}\n          />\n        ))}\n      </ActionMenu>\n\n      <ActionMenu\n        placement=\"bottom-start\"\n        scrollable={false}\n        renderTrigger={() => (\n          <Button\n            variant=\"secondary\"\n            title=\"Filtres rapides\"\n            endIcon=\"ChevronDown\"\n            selected={filtresRapidesFilter.length > 0}\n          />\n        )}\n      >\n        {filtresRapides.map(filtre => (\n          <ActionMenu.Item\n            key={filtre}\n            title={filtre}\n            selected={filtresRapidesFilter.includes(filtre)}\n            onPress={() =>\n              setFiltresRapidesFilter(prev =>\n                prev.includes(filtre) ? prev.filter(f => f !== filtre) : [...prev, filtre],\n              )\n            }\n          />\n        ))}\n      </ActionMenu>\n    </Box>\n  );\n};";

export const storySources = {
  Default,
  Filters,
} as const;

export type StorySourceName = keyof typeof storySources;
