name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy docs
    runs-on: [self-hosted]
    container: node:lts@sha256:392e1e23f34da768d8d1f4e502b64f200d3be3465934d4b7930f57d7e2fc1989
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build @alveole/core
        run: npm run build --workspace=packages/core

      - name: Build @alveole/theme
        run: npm run build --workspace=packages/theme

      - name: Build @alveole/components
        run: npm run build --workspace=packages/components

      - name: Build @alveole/storybook
        run: npm run build --workspace=packages/storybook

      - name: Build docs
        run: npm run build --workspace=apps/docs

      - name: Disable Jekyll (allow _expo/ assets)
        run: touch apps/docs/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/docs/dist
          cname: alveole.captive.fr
